FROM python:3.10-slim-bookworm@sha256:68d914ec641a0b69267ce65184d000a2bc3a9ee2590ab702b82250ab2385735a
WORKDIR /airbyte/integration_code
ENV PYTHONUNBUFFERED=1
ENV AIRBYTE_ENTRYPOINT="python /airbyte/integration_code/main.py"
COPY requirements.lock ./
RUN pip install --no-cache-dir -r requirements.lock
COPY source_posthog ./source_posthog
COPY main.py ./
ENTRYPOINT ["python", "/airbyte/integration_code/main.py"]
