FROM docker.io/airbyte/source-declarative-manifest:7.28.4@sha256:da2dee37f8b6532edfcbde6b5402a14e5d7364b2b7dbfbcb61e9cad85c25fe63
COPY manifest.yaml components.py /airbyte/integration_code/source_declarative_manifest/
COPY trial_entrypoint.py /airbyte/integration_code/trial_entrypoint.py
ENV AIRBYTE_ENTRYPOINT="python /airbyte/integration_code/trial_entrypoint.py"
ENTRYPOINT ["python", "/airbyte/integration_code/trial_entrypoint.py"]
